language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.2
  - DJANGO=Django==1.5.0
  - DJANGO=https://github.com/django/django/tarball/stable/1.6.x

install:
  - pip install --use-mirrors $DJANGO

script: python setup.py test
